import type { RawProject } from "@/lib/projects";

type EyecatchSource = Pick<RawProject, "ogImage" | "liveUrl">;

/** Picks the card's eyecatch image URL.
 *
 *  Priority: explicit ogImage → OGP scraped from liveUrl → null (emoji fallback).
 *  ogImage wins even when liveUrl exists because some public sites cannot be
 *  fetched from the server side (sites where Vercel Firewall bot_protection returns
 *  a challenge answer 429 to every User-Agent, so scraping never works).
 */
export function eyecatchSrc(project: EyecatchSource): string | null {
  if (project.ogImage) return project.ogImage;
  if (project.liveUrl) return `/api/ogp?url=${encodeURIComponent(project.liveUrl)}`;
  return null;
}

const GENERATED_PREFIX = "/api/og/";
const GENERATED_SUFFIX = ".png";

/** Ids of projects whose eyecatch is generated by /api/og/[id] (prerendered at build time). */
export function generatedEyecatchIds(projects: { id: string; ogImage?: string }[]): string[] {
  return projects
    .filter((p) => p.ogImage === `${GENERATED_PREFIX}${p.id}${GENERATED_SUFFIX}`)
    .map((p) => p.id);
}

/** Route param of /api/og/[id] → project id. Accepts both "<id>.png" and the older "<id>". */
export function projectIdFromEyecatchParam(param: string): string {
  return param.endsWith(GENERATED_SUFFIX) ? param.slice(0, -GENERATED_SUFFIX.length) : param;
}
